Traceback (most recent call last):
  File "D:\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "D:\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "D:\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Read in SMS Spam Collection text from Github
url = 'https://github.com/bradybr/practical-data-science-and-ml/blob/main/datasets/SMS%20Spam%20Collection.csv?raw=true'
dat = pd.read_csv(url, encoding = 'unicode_escape')['text']
dat.head(15)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[7], line 3[0m
[0;32m      1[0m [38;5;66;03m# Read in SMS Spam Collection text from Github[39;00m
[0;32m      2[0m url [38;5;241m=[39m [38;5;124m'[39m[38;5;124mhttps://github.com/bradybr/practical-data-science-and-ml/blob/main/datasets/SMS[39m[38;5;124m%[39m[38;5;124m20Spam[39m[38;5;124m%[39m[38;5;124m20Collection.csv?raw=true[39m[38;5;124m'[39m
[1;32m----> 3[0m dat [38;5;241m=[39m pd[38;5;241m.[39mread_csv(url, encoding [38;5;241m=[39m [38;5;124m'[39m[38;5;124municode_escape[39m[38;5;124m'[39m)[[38;5;124m'[39m[38;5;124mtext[39m[38;5;124m'[39m]
[0;32m      4[0m dat[38;5;241m.[39mhead([38;5;241m15[39m)

[1;31mNameError[0m: name 'pd' is not defined

